name: flutter_caffe_ku
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.6
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
